Prepare for eventual update to sshd-core but not now because of [FTPSERVER-437] NoSuchMethodError when using FtpServer 1.0.6 with SshD 0.8.0 because of dependency on different mina-core versions.
git-svn-id: https://svn.apache.org/repos/asf/commons/proper/vfs/trunk@1403417 13f79535-47bb-0310-9956-ffa450edef68